@startuml

class Handler{
  Handler successor;
 void  processRequest();
}

Request <-- Handler
Handler o-- Handler

Handler <|-- ConcreteHandlerA
Handler <|-- ConcreteHandlerB

Handler <--  Client
Request <--  Client

class ConcreteHandlerA{
  void  processRequest();
}
class ConcreteHandlerB{
  void  processRequest();
}
@enduml